### ISSUE TITLE
GATK-SV HPC 

### ISSUE THREAD

**Issue by srynobio** [broadinstitute/gatk-sv#132]
I just have a quick question:

Based on your listed [requirements](https://github.com/broadinstitute/gatk-sv#requirements), it show that a google cloud account is required.  I just wanted to confirm this is the case, and if HPC environments will be supported in the future.

Thanks in advance.

**Comment by epiercehoffman** [comment]
GATK-SV is designed to be run in Google Cloud, and some of the modules will not work as-is on local clusters due to the way Cromwell handles glob calls. We don't have plans to support HPC / local cluster backend environments.

Some users have attempted to run GATK-SV on SLURM clusters, using Singularity instead of Docker. There has been some success with Module00a, but other modules would require modification. I'll refer you to another issue #39 with a few more details on that.
