### ISSUE TITLE
VCFCluster Hang on particular regions

### ISSUE THREAD

**Issue by NTNguyen13** [broadinstitute/gatk-sv#196]
### Instructions

The github issue tracker is for bug reports and feature requests.
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

### Affected module(s) or script(s)
- Module 00c - VCFCluster Script - Delly Input

### Affected version(s)
- Current version

### Description 
- I ran the module00c before on a small dataset (50 samples) without any problem, but in a larger dataset (1000 samples), the VCFCluster script seems to be hanging forever on some regions of the genomes. It keeps running without generating more variant or any error and warning.
- I used the lifted-over blacklist regions (from hg19 to hg38) from the main paper. For example, in chromosome 20, it seems to be stuck on regions 30419232-31216078, with the last output variant at position 31000848.  I tried to 'move' the black list regions to narrow down the problem and it seems like the script stuck on the whole range from 31053000 to 31216078.
- My VCF file is standardized.

Could you please give me some insight on this problem? Thank you very much

**Comment by epiercehoffman** [comment]
Hi, I'm not sure if you're still dealing with this issue because it took us a while to get to it. But I'll offer a few notes:
* Module00c (now renamed to GatherBatchEvidence) should be run on batches of up to 500 samples. So for a 1000-sample cohort, we would recommend splitting that into at least 2 batches for this step. Please see our updated README for guidance on batching: https://github.com/broadinstitute/gatk-sv#cohort-mode
* We are in the process of deprecating our support for Delly. We have observed an overabundance of calls from Delly for some cohorts, and similar calls are captured by Manta and Wham, so our latest cohorts have been processed without Delly. Removing Delly may solve your issue.
* Our most up-to-date lists of regions to exclude (as well as other hg38 reference resources) can be found here: https://github.com/broadinstitute/gatk-sv/blob/master/input_values/resources_hg38.json
