### ISSUE TITLE
Clean Current Workspace before Start

### ISSUE THREAD

**Issue by henriqueribeiro** [broadinstitute/gatk-sv#284]
Hi. 

I've been running the GATK-SV pipeline with AWS backend and, sometimes, due to some intermittent errors the tasks are aborted half-way trough. Then Cromwell re-launches the task but some files, generated by the previous run, are already there what makes the pipeline to fail. With this in mind, I'm preparing do a change in cromwell that remove all the files (except for the script which gets created for each run/job) from the task folder before it starts and I would like to ask:
1. if this makes sense?
2. if there is any problem on doing this. can the same folder be used twice? or does each task has its own “workspace”? or Will this change impact any other downstream jobs as we will remove everything except “script” file?

Thanks in advance

**Comment by epiercehoffman** [comment]
Since this is a cromwell issue, I would direct your questions to cromwell developers. We don't see this issue with GCP, and I believe that is because files from the previous attempt are not carried over to the new VM in GCP as you suggest, but I can't comment on the details of the implementation and I think the cromwell developers would have more insight.

**Comment by henriqueribeiro** [comment]
Thanks @epiercehoffman
