### ISSUE TITLE
Running with Docker Image 

### ISSUE THREAD

**Issue by vaderhhh** [broadinstitute/gatk-sv#39]
Hi,

My cluster doesn't support Docker, is there a way to run this on Singularity or is the only way to port the WDLs to change the Docker paths to local paths? 

Thanks, 
Luke

**Comment by cwhelan** [comment]
It should theoretically be possible to run this in Singularity containers on a cluster but we've never tried it in practice. You'd have to configure a cromwell installation for it, and you might want to pre-build Singularity files for all of the docker images we use in the pipeline. The repo https://github.com/broadinstitute/uger-cromwell has some scripts and instructions for running WDL applications with Cromwell and Singularity on the Broad's UGER cluster; you might be able to modify its instructions for your particular cluster environment.

**Comment by mwalker174** [comment]
We have been able to get Module00a running on a SLURM cluster using Singularity, following some of the [Cromwell documentation.](https://cromwell.readthedocs.io/en/stable/tutorials/Containers/#singularity) Some of the other modules won't currently run on local clusters, however (due to the way Cromwell handles `glob` calls).

I'm going to close this issue since we don't plan on supporting Singularity / local cluster backends.
