### ISSUE TITLE
Question about Cross-Batch VCF merging

### ISSUE THREAD

**Issue by MattWellie** [broadinstitute/gatk-sv#530]
## Question

Tagging @VJalili 

Refers to the script which combines a cohort and Batch VCF file: https://github.com/broadinstitute/gatk-sv/blob/main/src/sv-pipeline/04_variant_resolution/scripts/add_batch_samples.py#L26-L33

We're redrafting this step a little in order to pre-combine VCF files from multiple batches to create the Cohort VCF. The script as written takes 2 files and merges them, but for workflows with n>2 batches, we'll need to pre-create the `Cohort VCF`.

Can I ask why in this highlighted section the logic is:

1. Load Cohort VCF
2. Load Batch VCF
3. Take all header lines except for the Sample line from the Cohort VCF
4. Take the Sample line from the Header of the Batch VCF

Couldn't this be simplified to `take all header lines from the Batch VCF`?

This also arbitrarily sets the first Batch sample to be Heterozygous for all Cohort variants, though I'm assuming the downstream results aren't affected by who the genotype is assigned to? 🤷

**Comment by epiercehoffman** [comment]
The step that creates a cohort VCF by merging sites from multiple batches is [MergeBatchSites](https://github.com/broadinstitute/gatk-sv/blob/main/wdl/MergeBatchSites.wdl), which should be run before GenotypeBatch to generate the cohort sites VCF. I believe this step is what you are looking for - you shouldn't need to write your own code to generate the cohort VCF.

To address your other questions:

- The add_batch_samples script you linked adds the batch's samples to the cohort sites VCF so that the VCF contains the samples and the sites in the same place.
- The genotypes do not matter at this point because they will be determined during the rest of the GenotypeBatch workflow.
- In most cases it would be equivalent to take all header lines from the batch VCF, although they should be about the same in terms of efficiency. I guess if you needed to edit the header at this stage, it would be nice to be able to edit the cohort VCF header once, rather than editing every batch's VCF header.

**Comment by MattWellie** [comment]
Thanks @epiercehoffman, I hadn't seen MergeBatchSites included in any of the higher level WDL files 👌

**Comment by MattWellie** [comment]
Hi @epiercehoffman, we've (finally) got the point where we're running this in anger and I can't get it to play nicely. I've raised #564, it would be great to get any input you might have to help solve!
