### ISSUE TITLE
Out of memory at CNMOPS in SingleSample mode

### ISSUE THREAD

**Issue by boboppie** [broadinstitute/gatk-sv#61]
Dear developers,

I'm trying to run the SingleSample pipeline example (inputs/GATKSVPipelineSingleSample.ref_panel_1kg.na12878.no_melt.json), however the pipeline run was killed due to an out-of-memory issue. Please see the detail in the following:

### Affected module(s) or script(s)
module: Module00c > CNMOPS or CNMOPSLarge
script: 
- runcnMOPS.R
- cnMOPS_workflow.sh
- CNMOPS.wdl

### Affected version(s)
- master branch cloned on 15-Sep-2020

### Description
I noticed that a few R processes for runcnMOPS.R took all the memory (120G), but it's not clear why this happened and how to adjust the number of processes?

![image](https://user-images.githubusercontent.com/543789/95060485-3bcbdb00-06f2-11eb-9305-8a8247b37cb6.png)

Please will you advise?

Best wishes,
Fengyuan

**Comment by boboppie** [comment]
Dear @cwhelan would you please let me know the max memory current SingleSample pipeline (ref_panel_1kg) needs? For example on a 8 core or 16 core machine.

**Comment by cwhelan** [comment]
When running with the 1000 Genomes reference panel we run the CNMOPS workflow scattered across VMs with either 16 or 24GB RAM and only use one core in each VM. If running on the Google cloud, the amount of memory requested can be adjusted using the optional `cnmops_mem_gb_override_sample3` input parameter to the single sample pipeline. We run a 16GB and a 24GB RAM job for each chromosome (twice for the allosomes). Since we typically only run on Google cloud instances, and each task is run on a different VM with different memory sizes, there isn't really a 'max memory' for the pipeline. 

It looks like you are trying to run the pipeline on a single machine locally; is that the case? If so, your cromwell instance may be trying to spawn all of these high memory jobs simultaneously. We can't provide detailed support for running the pipeline locally, since we don't run it that way ourselves, but you may want to experiment with cromwell options such as `concurrent-job-limit` to keep cromwell from exhausting your resources by launching too many simultaneous jobs.

**Comment by boboppie** [comment]
Dear @cwhelan , thank you for your reply. Yes, we are running it locally as a test. I'll try to experiment with concurrent-job-limit to see if it improve the performance.
