### ISSUE TITLE
Single sample mode results benchmarking

### ISSUE THREAD

**Issue by boboppie** [broadinstitute/gatk-sv#74]
Dear @cwhelan,

We have run SS model for two samples - HG00514 and HG002, both have been extensively studied for SV. We compared the results to the truesets, however the outcome looks poor. I'm wondering if there's something we missed:

- Is there a "best practice" or set of parameters we can tweak for SS? It looks the parameters in the json input file are already tuned.  
- Is the 1KGP reference panel based on low coverage sequences? I noticed someone asked about NYGC high-cov data (https://github.com/broadinstitute/gatk-sv/issues/73), will high-cov sequences improve the calling significantly?
- I assume Broad is running gatk-sv in batch mode using high-cov sequences? Is it the case?

Would you please share your ideas?

Best wishes,
Fengyuan

**Comment by cwhelan** [comment]
Hi @boboppie ,

Can you characterize the performance you're seeing a little? Are you seeing an excess of false positives or false negatives? 

If it's false positives, make sure you're only variants with PASS in the filter field.

One thing that might help to diagnose an issue would be if you could post the `qc_file` outputs from your pipeline. These provide some raw metrics on the coverage biases, evidence counts, and number of variants called in different categories.

The input parameters in the JSON file are tuned based on our runs of the joint-calling pipeline that created the reference panels. I wouldn't recommend tweaking any of the individual parameters for a single run.

The 1KGP reference panel is constructed from 156 of the high coverage NYGC samples (~20-30X coverage). 

We've sometimes seen poor performance in CNV calling if the input sample differs substantially from the reference panel samples in some way, usually in coverage depth or WGD coverage bias score (see https://github.com/RCollins13/WGD). Outliers in coverage bias can be due to different library preparations (ie sample libraries constructed with PCR amplification protocols as opposed to the more modern PCR-free preparations used by Broad and NYGC) or if the DNA extraction degraded some of the input DNA or added some other bias. Can you describe the input data you used for HG0014 and HG002? Do you know the coverage, library preparation, etc?

We are regularly running the pipeline in both joint and single sample mode on high coverage (20-30x) Novaseq PCR-free samples. The full joint pipeline includes a batching mode that tries to group together samples with similar coverage bias scores, which is how we generate call sets from very heterogeneous sample sets, such as gnomAD.

**Comment by boboppie** [comment]
Hi @cwhelan ,

Thank you for your quick reply. 

In terms of characterising the performance, I would say that we see excess false negatives compared to other callers (DRAGEN-SV and Parliament2), and that this is observed whether we consider PASS-only calls (HG002) or all calls (HG00514). 

### QC reports:
HG00514 (2-4X, PCR-free):
```
#METRIC MIN     MAX     VALUE   RESULT
wgd_score_sample        -0.1053 0.1208  -0.00155658527387417    PASS
sr_left_sample  4166678.0       75457545.8      5027203.0       PASS
sr_right_sample 4169899.2       75377368.3      5029831.0       PASS
pe_LL_sample    539588.1        6337340.5       1572269.0       PASS
pe_RR_sample    396180.7        6876821.2       1307838.0       PASS
pe_LR_sample    1379831.1       13423140.6      2100338.0       PASS
pe_RL_sample    592065.5        7370520.4       1751335.0       PASS
rd_q25_sample   10.0    49.2    19.0    PASS
rd_q50_sample   12.8    54.8    22.0    PASS
rd_q75_sample   15.8    60.6    26.0    PASS
final_vcf_DEL_pass_count        2761.0  3534.0  2578.0  FAIL
final_vcf_DEL_pass_size_0_500   2038.0  3009.0  1985.0  FAIL
final_vcf_DEL_pass_size_500_5000        490.0   917.0   423.0   FAIL
final_vcf_DEL_pass_size_5000_100000     140.0   261.0   162.0   PASS
final_vcf_DEL_pass_size_gte_100000      0.0     28.1    8.0     PASS
final_vcf_DUP_pass_count        387.6   1246.0  505.0   PASS
final_vcf_DUP_pass_size_0_500   279.5   1073.0  418.0   PASS
final_vcf_DUP_pass_size_500_5000        0.0     1291.5  29.0    PASS
final_vcf_DUP_pass_size_5000_100000     36.3    195.6   53.0    PASS
final_vcf_DUP_pass_size_gte_100000      0.0     17.5    5.0     PASS
final_vcf_INS_pass_count        606.6   2856.0  829.0   PASS
final_vcf_INS_pass_size_0_500   570.2   2676.0  821.0   PASS
final_vcf_INS_pass_size_500_5000        24.9    142.0   8.0     FAIL
final_vcf_INS_pass_size_5000_100000     0.0     34.6    0.0     PASS
final_vcf_INS_pass_size_gte_100000      0.0     10.0    0.0     PASS
final_vcf_INV_pass_count        0.0     18.8    10.0    PASS
final_vcf_INV_pass_size_0_500   0.0     10.0    5.0     PASS
final_vcf_INV_pass_size_500_5000        0.0     14.9    4.0     PASS
final_vcf_INV_pass_size_5000_100000     0.0     10.0    1.0     PASS
final_vcf_INV_pass_size_gte_100000      0.0     10.0    0.0     PASS
final_vcf_CPX_pass_count        0.0     80.2    28.0    PASS
final_vcf_CPX_pass_size_0_500   0.0     25.9    4.0     PASS
final_vcf_CPX_pass_size_500_5000        0.0     35.3    20.0    PASS
final_vcf_CPX_pass_size_5000_100000     0.0     10.0    3.0     PASS
final_vcf_CPX_pass_size_gte_100000      0.0     10.0    1.0     PASS
final_vcf_BND_count     522.0   1300.0  1212.0  PASS
```
HG002 (50X, PCR-free):
```
#METRIC MIN     MAX     VALUE   RESULT
wgd_score_sample        -0.1053 0.1208  -0.368513876271002      FAIL
sr_left_sample  4166678.0       75457545.8      9412020.0       PASS
sr_right_sample 4169899.2       75377368.3      9412135.0       PASS
pe_LL_sample    539588.1        6337340.5       2930301.0       PASS
pe_RR_sample    396180.7        6876821.2       3076549.0       PASS
pe_LR_sample    1379831.1       13423140.6      9228583.0       PASS
pe_RL_sample    592065.5        7370520.4       8560043.0       FAIL
rd_q25_sample   10.0    49.2    30.0    PASS
rd_q50_sample   12.8    54.8    36.0    PASS
rd_q75_sample   15.8    60.6    43.0    PASS
final_vcf_DEL_pass_count        2761.0  3534.0  2775.0  PASS
final_vcf_DEL_pass_size_0_500   2038.0  3009.0  2130.0  PASS
final_vcf_DEL_pass_size_500_5000        490.0   917.0   472.0   FAIL
final_vcf_DEL_pass_size_5000_100000     140.0   261.0   165.0   PASS
final_vcf_DEL_pass_size_gte_100000      0.0     28.1    8.0     PASS
final_vcf_DUP_pass_count        387.6   1246.0  556.0   PASS
final_vcf_DUP_pass_size_0_500   279.5   1073.0  484.0   PASS
final_vcf_DUP_pass_size_500_5000        0.0     1291.5  23.0    PASS
final_vcf_DUP_pass_size_5000_100000     36.3    195.6   47.0    PASS
final_vcf_DUP_pass_size_gte_100000      0.0     17.5    2.0     PASS
final_vcf_INS_pass_count        606.6   2856.0  713.0   PASS
final_vcf_INS_pass_size_0_500   570.2   2676.0  711.0   PASS
final_vcf_INS_pass_size_500_5000        24.9    142.0   2.0     FAIL
final_vcf_INS_pass_size_5000_100000     0.0     34.6    0.0     PASS
final_vcf_INS_pass_size_gte_100000      0.0     10.0    0.0     PASS
final_vcf_INV_pass_count        0.0     18.8    10.0    PASS
final_vcf_INV_pass_size_0_500   0.0     10.0    6.0     PASS
final_vcf_INV_pass_size_500_5000        0.0     14.9    4.0     PASS
final_vcf_INV_pass_size_5000_100000     0.0     10.0    0.0     PASS
final_vcf_INV_pass_size_gte_100000      0.0     10.0    0.0     PASS
final_vcf_CPX_pass_count        0.0     80.2    21.0    PASS
final_vcf_CPX_pass_size_0_500   0.0     25.9    2.0     PASS
final_vcf_CPX_pass_size_500_5000        0.0     35.3    15.0    PASS
final_vcf_CPX_pass_size_5000_100000     0.0     10.0    4.0     PASS
final_vcf_CPX_pass_size_gte_100000      0.0     10.0    0.0     PASS
final_vcf_BND_count     522.0   1300.0  1252.0  PASS
```
In this case, we used a low-cov HG00514 sample (2-4X), but we are preparing to run this sample again with a high-cov (30X) version.

Please would you share your thoughts?

Thanks,
Fengyuan

**Comment by cwhelan** [comment]
Hi Fengyuan,

Thanks for posting the metrics. Here are a few thoughts:

* You're right that the pipeline seems to have low sensitivity on these samples. We usually benchmark against against an NA19240 sample and currently see ~5700 PASS variants called vs the 4075 you are seeing here. Some of that could be due to the difference in ancestry between the samples but that would not explain most of the drop.
* The pipeline is designed for medium to high-coverage WGS data (20-40x generally). It probably won't work well on 2-4X low coverage samples like your HG00514.
* The WGD dosage score (`wgd_score_sample`) for your HG002 sample,  at -0.36, is quite a bit outside the range of scores we see in our 1000 Genomes reference panel that we are joint calling with. Samples that are outside of that range often produce unexpected results in joint genotyping. It may be that the sample is too different from the reference panel to allow accurate calling. Is the BAM or CRAM file you are using public data, or something that you sequenced in-house? We are working on adding more automatic QC checks to the pipeline that will flag samples that fail this type of compatibility check with the reference panel more forcefully. 
* The pipeline was built to be sensitive but also to have a low FDR for called variants. Are you seeing low specificity in your evaluation as well?
